export interface Course {
  number: string
  name: string
  pdf?: string
}

export const courseData: Record<string, { title: string; courses: Course[]; headerColor: string }> = {
  energia: {
    title: "Energía",
    headerColor: "#B8860B",
    courses: [
      { number: "1", name: "Diagnósticos Energéticos Residenciales",pdf:"/pdf/ELECTRICIDAD/1.1.pdf"},
      { number: "2", name: "Diagnósticos Energéticos Empresariales",pdf:"/pdf/ELECTRICIDAD/1.2.pdf"},
      { number: "3", name: "Alumbrado público eficiente" },
      { number: "4", name: "Código de red",pdf:"/pdf/ELECTRICIDAD/1.4.pdf" },
      { number: "5", name: "Compraventa de Energía en Mercados eléctricos.",pdf:"/pdf/ELECTRICIDAD/1.5.pdf"},
      { number: "6", name: "Control de la Demanda Eléctrica",pdf:"/pdf/ELECTRICIDAD/1.6.pdf"},
      { number: "7", name: "Cortocircuito y Coordinación de Protecciones.",pdf:"/pdf/ELECTRICIDAD/1.7.pdf"},
      { number: "8", name: "Edificación sustentable",pdf:"/pdf/ELECTRICIDAD/1.8.pdf"},
      { number: "9", name: "Eficiencia en Aire Acondicionado y Refrigeración",pdf:"/pdf/ELECTRICIDAD/1.9.pdf"},
      { number: "10", name: "Evaluación de Proyectos de Energía",pdf:"/pdf/ELECTRICIDAD/1.10.pdf"},
      { number: "11", name: "Factor de potencia y demanda",pdf:"/pdf/ELECTRICIDAD/1.11.pdf" },
      { number: "12", name: "Generación Y Ahorro De Energia Con Paneles Fotovoltaicos",pdf:"/pdf/ELECTRICIDAD/1.12.pdf" },
      { number: "13", name: "Gestión de la energía" },
      { number: "14", name: "Introducción a energías limpias",pdf:"/pdf/ELECTRICIDAD/1.14.pdf"},
      { number: "15", name: "Oportunidades de la Reforma Energética" },
      { number: "16", name: "Motores, Variadores y Aire comprimido",pdf:"/pdf/ELECTRICIDAD/1.16.pdf" },
      { number: "17", name: "Eficiencia en Sistemas de Bombeo",pdf:"/pdf/ELECTRICIDAD/1.17.pdf" },
      { number: "18", name: "Calidad de la Energía Eléctrica",pdf:"/pdf/ELECTRICIDAD/1.18.pdf" },
      { number: "19", name: "Sistemas de Iluminación en inmuebles",pdf:"/pdf/ELECTRICIDAD/1.19.pdf" },
      { number: "20", name: "Filtrado y mitigación de armónicas",pdf:"/pdf/ELECTRICIDAD/1.20.pdf" },
      { number: "21", name: "Variaciones de voltaje",pdf:"/pdf/ELECTRICIDAD/1.21.pdf" },
      { number: "22", name: "Análisis Transitorio de Capacitores",pdf:"/pdf/ELECTRICIDAD/1.22.pdf" },
      { number: "23", name: "Compensación de potencia reactiva",pdf:"/pdf/ELECTRICIDAD/1.23.pdf"},
      { number: "24", name: "Corrección de factor de potencia",pdf:"/pdf/ELECTRICIDAD/1.24.pdf" },
      { number: "25", name: "Puesta a Tierra en Redes Eléctricas",pdf:"/pdf/ELECTRICIDAD/1.25.pdf" },
      { number: "26", name: "Electricidad básica",pdf:"/pdf/ELECTRICIDAD/1.26.pdf" },
      { number: "27", name: "Diagnósticos energéticos",pdf:"/pdf/ELECTRICIDAD/1.27.pdf" },
      { number: "28", name: "Gestión Energética bajo la ISO 50001" },
      { number: "29", name: "NOM 001-SEDE 2018 y Puesta a Tierra",pdf:"/pdf/ELECTRICIDAD/1.29.pdf" },
      { number: "30", name: "Subestaciones Eléctricas y Puesta Tierra",pdf:"/pdf/ELECTRICIDAD/1.30.pdf" },
      { number: "31", name: "Diseño de indicadores energéticos",pdf:"/pdf/ELECTRICIDAD/1.31.pdf"},
      { number: "32", name: "Tecnologías de Acondicionamiento ambiental" },
      { number: "33", name: "Generación Distribuida",pdf:"/pdf/ELECTRICIDAD/1.33.pdf" },
      { number: "34", name: "Normativa y regulación energética",pdf:"/pdf/ELECTRICIDAD/1.34.pdf" },
    ],
  },
  seguridad: {
    title: "Seguridad y Salud en el Trabajo",
    headerColor: "#0891B2",
    courses: [
      { number: "1", name: "NOM-002-STPS-2010",pdf:"/pdf/ENERGIA/2.1.pdf" },
      { number: "2", name: "NOM-004-STPS-1999",pdf:"/pdf/ENERGIA/2.2.pdf" },
      { number: "3", name: "NOM-005-STPS-1998",pdf:"/pdf/ENERGIA/2.3.pdf" },
      { number: "4", name: "NOM-006-STPS-2014",pdf:"/pdf/ENERGIA/2.4.pdf" },
      { number: "5", name: "NOM-009-STPS-2011",pdf:"/pdf/ENERGIA/2.5.pdf" },
      { number: "6", name: "NOM-017-STPS-2008",pdf:"/pdf/ENERGIA/2.7.pdf" },
      { number: "7", name: "NOM-018-STPS-2015",pdf:"/pdf/ENERGIA/2.8.pdf" },
      { number: "8", name: "NOM-019-STPS-2011",pdf:"/pdf/ENERGIA/2.9.pdf" },
      { number: "9", name: "NOM-022-STPS-2015",pdf:"/pdf/ENERGIA/2.10.pdf"},
      { number: "10", name: "NOM-025-STPS-2008",pdf:"/pdf/ENERGIA/2.11.pdf"},
      { number: "11", name: "NOM-026-STPS-2008",pdf:"/pdf/ENERGIA/2.12.pdf"},
      { number: "12", name: "NOM-027-STPS-2008",pdf:"/pdf/ENERGIA/2.13.pdf"},
      { number: "13", name: "NOM-029-STPS-2011",pdf:"/pdf/ENERGIA/2.14.pdf" },
      { number: "14", name: "NOM-030-STPS-2009",pdf:"/pdf/ENERGIA/2.15.pdf" },
      { number: "15", name: "NOM-035-STPS-2018",pdf:"/pdf/ENERGIA/2.16.pdf" },
      { number: "16", name: "NOM-036-1-STPS-2018",pdf:"/pdf/ENERGIA/2.17.pdf"},
      { number: "17", name: "Formación de Brigadas en Protección Civil" },
      { number: "18", name: "Primeros Auxilios" },
      { number: "19", name: "Prevención y combate de incendios" },
      { number: "20", name: "Evacuación de inmuebles" },
      { number: "21", name: "Manejo de residuos peligrosos" },
      { number: "22", name: "Manejo Seguro De Montacargas" },
      { number: "23", name: "Operacion De Equipo De Arrastre A Montacargas " },
      { number: "24", name: "Bloque,Candado Y Control De Energia Peligrosa" },
      { number: "25", name: "Atencion De Derrames" },
      { number: "26", name: "Manejo Integral De Residuos Peligrosos Biologicos" },
      { number: "27", name: "Sistema LOTO" },
      ,
    ],
  },
  "desarrollo-personal": {
    title: "Desarrollo Personal",
    headerColor: "#65A30D",
    courses: [
      { number: "1", name: "Autoestima" },
      { number: "2", name: "Asertividad" },
      { number: "3", name: "Comunicación efectiva" },
      { number: "4", name: "Desarrollo del pensamiento lógico" },
      { number: "5", name: "Programación neurolingüística" },
      { number: "6", name: "Relaciones Humanas" },
      { number: "7", name: "Administración del tiempo" },
    ],
  },
  "desarrollo-organizacional": {
    title: "Desarrollo Organizacional",
    headerColor: "#EA580C",
    courses: [
      { number: "1", name: "Liderazgo" },
      { number: "2", name: "Equipos de trabajo de alto rendimiento" },
      { number: "3", name: "Atención al cliente" },
      { number: "4", name: "Evaluación económica de proyectos" },
      { number: "5", name: "Análisis e interpretación de estados financieros" },
      { number: "6", name: "Manejo de conflictos" },
    ],
  },
  formativo: {
    title: "Formativo",
    headerColor: "#3B82F6",
    courses: [
      { number: "1", name: "Formación de instructores en cursos presenciales" },
      { number: "2", name: "Diseño de cursos y materiales didácticos" },
      { number: "3", name: "Formación de evaluadores de competencias" },
      { number: "4", name: "Diseño de Cursos en línea" },
    ],
  },
  valuacion: {
    title: "Valuación",
    headerColor: "#6B7280",
    courses: [
      { number: "1", name: "Valuación de alhajas, relojes y joyas",pdf:"/pdf/VALUACION/5.1.pdf"},
      { number: "2", name: "Valuación de vehículos sin resguardo",pdf:"/pdf/VALUACION/5.2.pdf" },
      { number: "3", name: "Valuación de artículos varios" },
    ],
  },
}


