export interface Course {
  number: string
  name: string
  pdf?: string
}

export const courseData: Record<string, { title: string; courses: Course[]; headerColor: string }> = {
  energia: {
    title: "Energía",
    headerColor: "#B8860B",
    courses: [
      { number: "1", name: "Diagnósticos Energéticos Residenciales",pdf:"/pdf/ELECTRICIDAD/1.1.pdf"},
      { number: "2", name: "Diagnósticos Energéticos Empresariales",pdf:"/pdf/ELECTRICIDAD/1.2.pdf"},
      { number: "3", name: "Alumbrado público eficiente" },
      { number: "4", name: "Código de red" },
      { number: "5", name: "Compraventa de Energía en Mercados eléctricos.",pdf:"/pdf/ELECTRICIDAD/1.5.pdf"},
      { number: "6", name: "Control de la Demanda Eléctrica" },
      { number: "7", name: "Cortocircuito y Coordinación de Protecciones.",pdf:"/pdf/ELECTRICIDAD/1.7.pdf"},
      { number: "8", name: "Edificación sustentable",pdf:"/pdf/ELECTRICIDAD/1.8.pdf"},
      { number: "9", name: "Eficiencia en Aire Acondicionado y Refrigeración",pdf:"/pdf/ELECTRICIDAD/1.9.pdf"},
      { number: "10", name: "Evaluación de Proyectos de Energía",pdf:"/pdf/ELECTRICIDAD/1.10.pdf"},
      { number: "11", name: "Factor de potencia y demanda" },
      { number: "12", name: "Generación Y Ahorro De Energia Con Paneles Fotovoltaicos",pdf:"/pdf/ELECTRICIDAD/1.12.pdf" },
      { number: "13", name: "Gestión de la energía" },
      { number: "14", name: "Introducción a energías limpias",pdf:"/pdf/ELECTRICIDAD/1.14.pdf"},
      { number: "15", name: "Oportunidades de la Reforma Energética" },
      { number: "16", name: "Motores, Variadores y Aire comprimido",pdf:"/pdf/ELECTRICIDAD/1.16.pdf" },
      { number: "17", name: "Eficiencia en Sistemas de Bombeo" },
      { number: "18", name: "Calidad de la Energía Eléctrica" },
      { number: "19", name: "Sistemas de Iluminación en inmuebles" },
      { number: "20", name: "Filtrado y mitigación de armónicas",pdf:"/pdf/ELECTRICIDAD/1.20.pdf" },
      { number: "21", name: "Variaciones de voltaje" },
      { number: "22", name: "Análisis Transitorio de Capacitores",pdf:"/pdf/ELECTRICIDAD/1.22.pdf" },
      { number: "23", name: "Compensación de potencia reactiva",pdf:"/pdf/ELECTRICIDAD/1.23.pdf"},
      { number: "24", name: "Corrección de factor de potencia" },
      { number: "25", name: "Puesta a Tierra en Redes Eléctricas" },
      { number: "26", name: "Electricidad básica",pdf:"/pdf/ELECTRICIDAD/1.26.pdf" },
      { number: "27", name: "Diagnósticos energéticos",pdf:"/pdf/ELECTRICIDAD/1.27.pdf" },
      { number: "28", name: "Gestión Energética bajo la ISO 50001" },
      { number: "29", name: "NOM 001-SEDE 2018 y Puesta a Tierra" },
      { number: "30", name: "Subestaciones Eléctricas y Puesta Tierra" },
      { number: "31", name: "Diseño de indicadores energéticos",pdf:"/pdf/ELECTRICIDAD/1.31.pdf"},
      { number: "32", name: "Tecnologías de Acondicionamiento ambiental" },
      { number: "33", name: "Generación Distribuida",pdf:"/pdf/ELECTRICIDAD/1.33.pdf" },
      { number: "34", name: "Normativa y regulación energética" },
    ],
  },
  seguridad: {
    title: "Seguridad y Salud en el Trabajo",
    headerColor: "#0891B2",
    courses: [
      { number: "1", name: "NOM-002-STPS-2010" },
      { number: "2", name: "NOM-004-STPS-1999" },
      { number: "3", name: "NOM-005-STPS-1998" },
      { number: "4", name: "NOM-006-STPS-2014" },
      { number: "5", name: "NOM-009-STPS-2011" },
      { number: "6", name: "NOM-009-STPS-2011" },
      { number: "7", name: "NOM-017-STPS-2008" },
      { number: "8", name: "NOM-018-STPS-2015" },
      { number: "9", name: "NOM-019-STPS-2011" },
      { number: "10", name: "NOM-022-STPS-2015" },
      { number: "11", name: "NOM-025-STPS-2008" },
      { number: "12", name: "NOM-026-STPS-2008" },
      { number: "13", name: "NOM-027-STPS-2008" },
      { number: "14", name: "NOM-029-STPS-2011" },
      { number: "15", name: "NOM-030-STPS-2009" },
      { number: "16", name: "NOM-035-STPS-2018" },
      { number: "17", name: "NOM-036-1-STPS-2018" },
      { number: "18", name: "Formación de Brigadas en Protección Civil" },
      { number: "19", name: "Primeros Auxilios" },
      { number: "20", name: "Prevención y combate de incendios" },
      { number: "21", name: "Evacuación de inmuebles" },
      { number: "22", name: "Manejo de residuos peligrosos" },
      { number: "23", name: 'Manejo Residual: Acumuladores de Ion Litio"' },
    ],
  },
  "desarrollo-personal": {
    title: "Desarrollo Personal",
    headerColor: "#65A30D",
    courses: [
      { number: "1", name: "Autoestima" },
      { number: "2", name: "Asertividad" },
      { number: "3", name: "Comunicación efectiva" },
      { number: "4", name: "Desarrollo del pensamiento lógico" },
      { number: "5", name: "Programación neurolingüística" },
      { number: "6", name: "Relaciones Humanas" },
      { number: "7", name: "Administración del tiempo" },
    ],
  },
  "desarrollo-organizacional": {
    title: "Desarrollo Organizacional",
    headerColor: "#EA580C",
    courses: [
      { number: "1", name: "Liderazgo" },
      { number: "2", name: "Equipos de trabajo de alto rendimiento" },
      { number: "3", name: "Atención al cliente" },
      { number: "4", name: "Evaluación económica de proyectos" },
      { number: "5", name: "Análisis e interpretación de estados financieros" },
      { number: "6", name: "Manejo de conflictos" },
    ],
  },
  formativo: {
    title: "Formativo",
    headerColor: "#3B82F6",
    courses: [
      { number: "1", name: "Formación de instructores en cursos presenciales" },
      { number: "2", name: "Diseño de cursos y materiales didácticos" },
      { number: "3", name: "Formación de evaluadores de competencias" },
      { number: "4", name: "Diseño de Cursos en línea" },
    ],
  },
  valuacion: {
    title: "Valuación",
    headerColor: "#6B7280",
    courses: [
      { number: "1", name: "Valuación de alhajas, relojes y joyas" },
      { number: "2", name: "Valuación de vehículos sin resguardo" },
      { number: "3", name: "Valuación de artículos varios" },
    ],
  },
}


